# Makefile.in generated by automake 1.12.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2012 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Copyright (c) 2000, 2010, Oracle and/or its affiliates. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Process this file with automake to create Makefile.in

am__make_dryrun = \
  { \
    am__dry=no; \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        echo 'am--echo: ; @echo "AM"  OK' | $(MAKE) -f - 2>/dev/null \
          | grep '^AM OK$$' >/dev/null || am__dry=yes;; \
      *) \
        for am__flg in $$MAKEFLAGS; do \
          case $$am__flg in \
            *=*|--*) ;; \
            *n*) am__dry=yes; break;; \
          esac; \
        done;; \
    esac; \
    test $$am__dry = yes; \
  }
pkgdatadir = $(datadir)/mysql
pkgincludedir = $(includedir)/mysql
pkglibdir = $(libdir)/mysql
pkglibexecdir = $(libexecdir)/mysql
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
target_triplet = x86_64-unknown-linux-gnu
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure COPYING \
	ChangeLog config.guess config.sub depcomp install-sh ltmain.sh \
	missing ylwrap
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/config/ac-macros/maintainer.m4 \
	$(top_srcdir)/config/ac-macros/alloca.m4 \
	$(top_srcdir)/config/ac-macros/check_cpu.m4 \
	$(top_srcdir)/config/ac-macros/character_sets.m4 \
	$(top_srcdir)/config/ac-macros/compiler_flag.m4 \
	$(top_srcdir)/config/ac-macros/plugins.m4 \
	$(top_srcdir)/config/ac-macros/ha_ndbcluster.m4 \
	$(top_srcdir)/config/ac-macros/large_file.m4 \
	$(top_srcdir)/config/ac-macros/misc.m4 \
	$(top_srcdir)/config/ac-macros/readline.m4 \
	$(top_srcdir)/config/ac-macros/ssl.m4 \
	$(top_srcdir)/config/ac-macros/zlib.m4 \
	$(top_srcdir)/config/ac-macros/lzo2.m4 \
	$(top_srcdir)/config/ac-macros/ncurses.m4 \
	$(top_srcdir)/config/ac-macros/perftools.m4 \
	$(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/include/my_config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
	$(RECURSIVE_CLEAN_TARGETS:-recursive=) tags TAGS ctags CTAGS \
	cscope distdir dist dist-all distcheck
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ABI_CHECK = abi_check
ACLOCAL = ${SHELL} /home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/missing --run aclocal-1.12
ALLOCA = 
AMTAR = $${TAR-tar}
AM_CFLAGS = 
AM_CXXFLAGS = 
AM_DEFAULT_VERBOSITY = 1
AR = ar
ARFLAGS = cru
AS = gcc -c
ASFLAGS = 
AUTOCONF = ${SHELL} /home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/missing --run autoconf
AUTOHEADER = ${SHELL} /home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/missing --run autoheader
AUTOMAKE = ${SHELL} /home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/missing --run automake-1.12
AVAILABLE_LANGUAGES = czech danish dutch english estonian french german greek hungarian italian japanese korean norwegian norwegian-ny polish portuguese romanian russian serbian slovak spanish swedish ukrainian
AWK = mawk
CC = gcc -std=gnu99
CCAS = gcc -std=gnu99
CCASDEPMODE = depmode=gcc3
CCASFLAGS = -g2 -O2 -fno-strict-aliasing -fno-omit-frame-pointer -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -DHAVE_TERM_H    -Wa,--noexecstack
CCDEPMODE = depmode=gcc3
CC_VERSION = gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
CFLAGS =  -g2 -O2 -fno-strict-aliasing -fno-omit-frame-pointer -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -DHAVE_TERM_H   -DUNIV_LINUX -DUNIV_LINUX
CHECK_PID = /bin/kill -0 $$PID > /dev/null 2> /dev/null
CHMOD = /bin/chmod
CLIENT_EXTRA_LDFLAGS = 
CLIENT_LIBS = -lcrypt -lnsl -lm  -L/home/lq/projects/dist/mysql/lib/ -lssl -lcrypto $(top_builddir)/zlib/libzlt.la 
CLIENT_THREAD_LIBS = -lpthread
CMP = /usr/bin/cmp
COMPILATION_COMMENT = Google MySQL 5.1.63 build 20140722.101421.5159ced
CONF_COMMAND = /home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/configure  '--host=' '--enable-assembler' '--enable-local-infile' '--enable-profiling' '--with-big-tables' '--without-manager' '--with-extra-charsets=all' '--with-mysqld-user=mysql' '--with-unix-socket-path=/var/lib/mysql/mysql.sock' '--with-pic' '--with-ssl=/home/lq/projects/dist/mysql' '--prefix=/home/lq/projects/dist/mysql' '--exec-prefix=/home/lq/projects/dist/mysql' '--libexecdir=/home/lq/projects/dist/mysql/sbin' '--libdir=/home/lq/projects/dist/mysql/lib' '--sysconfdir=/etc' '--datadir=/home/lq/projects/dist/mysql/share' '--localstatedir=/var/lib/mysql' '--infodir=/home/lq/projects/dist/mysql/share/info' '--includedir=/home/lq/projects/dist/mysql/include' '--enable-thread-safe-client' '--with-plugins=innodb_plugin,googlestats' '--with-lzo2-dir=bundled' '--with-ncurses-dir=bundled' '--with-readline' '--with-perftools-dir=bundled' '--enable-perftools-tcmalloc' '--with-comment=Google MySQL 5.1.63 build 20140722.101421.5159ced' '--with-zlib-dir=bundled' '--with-server-suffix=-google' '--without-embedded-server' '--without-vio' '--without-debug' '--without-docs' '--without-man' 'CC=gcc' 'CPP=cpp' 'CXX=g++' 'LD=ld' 'RANLIB=ranlib' 'AR=ar' 'CPPFLAGS=' 'LDFLAGS= -lrt ' 'STRIP=/bin/true' 'CFLAGS=-g2 -O2 -fno-strict-aliasing -fno-omit-frame-pointer -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -DHAVE_TERM_H' 'CXXFLAGS=-g2 -O2 -fno-strict-aliasing -fno-omit-frame-pointer -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -DHAVE_TERM_H' 'GETCONF=' 'host_alias='
CP = /bin/cp
CPP = cpp
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS =  -g2 -O2 -fno-strict-aliasing -fno-omit-frame-pointer -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -DHAVE_TERM_H   -fno-rtti
CXXLDFLAGS = 
CXX_VERSION = g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DIFF = /usr/bin/diff
DOT_FRM_VERSION = 6
DOXYGEN = no
DVIS = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FIND_PROC = /bin/ps wwwp $$PID | grep -v " grep" | grep -v mysqld_safe | grep -- "$$MYSQLD" > /dev/null
GETCONF = getconf
GREP = /bin/grep
GXX = yes
HOSTNAME = /bin/hostname
INNODB_DYNAMIC_CFLAGS = -DMYSQL_DYNAMIC_PLUGIN
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
KILL = /bin/kill
LD = ld
LDFLAGS =  -lrt  -rdynamic 
LD_VERSION_SCRIPT = -Wl,--version-script=$(top_builddir)/libmysql/libmysql.ver
LIBDL = -ldl 
LIBEDIT_LOBJECTS =  unvis.o vis.o strlcpy.o strlcat.o fgetln.o
LIBOBJS = 
LIBS = -lpthread -lcrypt -lnsl -lm  -lpthread 
LIBTOOL = libtool --preserve-dup-deps
LIB_EXTRA_CCFLAGS = 
LM_CFLAGS = 
LN = /bin/ln
LN_CP_F = /bin/ln -s
LTLIBOBJS = 
LZO_DEPS = -llzo2
LZO_INCLUDES = -I$(top_srcdir)/lzo/include/lzo
LZO_LIBS = $(top_builddir)/lzo/src/liblzo2.la
MACHINE_TYPE = x86_64
MAKEINDEX = no
MAKEINFO = ${SHELL} /home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/missing --run makeinfo
MAKE_BINARY_DISTRIBUTION_OPTIONS = 
MAKE_SHELL = /bin/sh
MKDIR_P = /bin/mkdir -p
MV = /bin/mv
MYSQLD_DEFAULT_SWITCHES = --skip-external-locking
MYSQLD_EXTRA_LDFLAGS = 
MYSQLD_EXTRA_LIBS = 
MYSQLD_USER = mysql
MYSQL_BASE_VERSION = 5.1
MYSQL_COPYRIGHT_YEAR = 2014
MYSQL_NO_DASH_VERSION = 5.1.63
MYSQL_PREVIOUS_BASE_VERSION = 5.0
MYSQL_SERVER_SUFFIX = -google
MYSQL_TCP_PORT = 3306
MYSQL_TCP_PORT_DEFAULT = 0
MYSQL_UNIX_ADDR = /var/lib/mysql/mysql.sock
MYSQL_U_SCORE_VERSION = 5.1.63
MYSQL_VERSION_ID = 50163
NCURSES_DEPS = -lncurses
NCURSES_INCLUDES = -I$(top_srcdir)/ncurses/include
NCURSES_LIBS = $(top_builddir)/ncurses/lib/libncurses.a
NDB_DEFS = 
NDB_LD_VERSION_SCRIPT = 
NDB_SCI_INCLUDES = 
NDB_SCI_LIBS = 
NDB_SHARED_LIB_MAJOR_VERSION = 3
NDB_SHARED_LIB_VERSION = 3:0:0
NDB_SIZEOF_CHAR = 
NDB_SIZEOF_CHARP = 
NDB_SIZEOF_INT = 
NDB_SIZEOF_LONG = 
NDB_SIZEOF_LONG_LONG = 
NDB_SIZEOF_SHORT = 
NDB_VERSION_BUILD = 63
NDB_VERSION_MAJOR = 5
NDB_VERSION_MINOR = 1
NDB_VERSION_STATUS = 
NM = nm
NOINST_LDFLAGS = -static
NON_THREADED_LIBS = -lcrypt -lnsl -lm 
OBJEXT = o
PACKAGE = mysql
PACKAGE_BUGREPORT = 
PACKAGE_NAME = MySQL Server
PACKAGE_STRING = MySQL Server 5.1.63
PACKAGE_TARNAME = mysql
PACKAGE_URL = 
PACKAGE_VERSION = 5.1.63
PATH_SEPARATOR = :
PDFLATEX = no
PDFMANUAL = 
PERFTOOLS_DEPS = -L$(top_builddir)/google-perftools -ltcmalloc
PERFTOOLS_INCLUDES = -I$(top_srcdir)/google-perftools/src/google
PERFTOOLS_LIBS = -L$(top_builddir)/google-perftools -ltcmalloc
PERL = /usr/bin/perl
PERL5 = /usr/bin/perl
PROTOCOL_VERSION = 10
PS = /bin/ps
RANLIB = ranlib
RM = /bin/rm
SAVE_ASFLAGS = 
SAVE_CC = gcc
SAVE_CFLAGS = -g2 -O2 -fno-strict-aliasing -fno-omit-frame-pointer -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -DHAVE_TERM_H
SAVE_CXX = g++
SAVE_CXXFLAGS = -g2 -O2 -fno-strict-aliasing -fno-omit-frame-pointer -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -I/home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/ncurses/include -DHAVE_TERM_H
SAVE_CXXLDFLAGS = 
SAVE_LDFLAGS =  -lrt 
SED = /bin/sed
SET_MAKE = 
SHARED_LIB_MAJOR_VERSION = 16
SHARED_LIB_VERSION = 16:0:0
SHELL = /bin/bash
STATIC_NSS_FLAGS = 
STRIP = /bin/true
SYSTEM_TYPE = unknown-linux-gnu
TAR = tar
TARGET_LINUX = true
TERMCAP_LIB = 
TEST_NDBCLUSTER = 
THREAD_LOBJECTS = thr_alarm.o thr_lock.o thr_mutex.o thr_rwlock.o my_pthread.o my_thr_init.o mf_keycache.o
VERSION = 5.1.63
WRAPLIBS = 
YACC = bison -y -p MYSQL
ZLIB_DEPS = -lz
ZLIB_INCLUDES = -I$(top_srcdir)/zlib
ZLIB_LIBS = $(top_builddir)/zlib/libzlt.la
abs_builddir = /home/lq/projects/src/github.com/youtube/vitess/third_party/mysql
abs_srcdir = /home/lq/projects/src/github.com/youtube/vitess/third_party/mysql
abs_top_builddir = /home/lq/projects/src/github.com/youtube/vitess/third_party/mysql
abs_top_srcdir = /home/lq/projects/src/github.com/youtube/vitess/third_party/mysql
ac_ct_CC = gcc
ac_ct_CXX = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=ustar -chf - "$$tardir"
am__untar = tar -xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
condition_dependent_plugin_includes =  -I$(top_srcdir)/storage/googlestats/ -I$(top_srcdir)/storage/heap/ -I$(top_srcdir)/storage/myisam/ -I$(top_srcdir)/storage/myisammrg/
condition_dependent_plugin_links =  storage/googlestats/ha_googlestats.cc storage/heap/ha_heap.cc storage/myisam/ha_myisam.cc storage/myisammrg/ha_myisammrg.cc
condition_dependent_plugin_modules =  ha_googlestats.cc ha_heap.cc ha_myisam.cc ha_myisammrg.cc
condition_dependent_plugin_objects =  ha_googlestats.o ha_heap.o ha_myisam.o ha_myisammrg.o
datadir = /home/lq/projects/dist/mysql/share
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
docs_dirs = 
dvidir = ${docdir}
exec_prefix = /home/lq/projects/dist/mysql
extra_docs = 
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = /home/lq/projects/dist/mysql/include
infodir = /home/lq/projects/dist/mysql/share/info
innodb_system_libs = -lrt
install_sh = ${SHELL} /home/lq/projects/src/github.com/youtube/vitess/third_party/mysql/install-sh
libdir = /home/lq/projects/dist/mysql/lib
libexecdir = /home/lq/projects/dist/mysql/sbin
libmysqld_dirs = 
localedir = ${datarootdir}/locale
localstatedir = /var/lib/mysql
lzo_dir = lzo
man1_files = 
man8_files = 
man_dirs = 
mandir = ${datarootdir}/man
mysql_pg_dirs = 
mysql_pg_distdirs = 
mysql_pg_unittest_dirs = 
mysql_plugin_defs = , builtin_csv_plugin, builtin_googlestats_plugin, builtin_heap_plugin, builtin_innodb_plugin_plugin, builtin_myisam_plugin, builtin_myisammrg_plugin
mysql_plugin_dirs = 
mysql_plugin_libs =  $(top_builddir)/storage/csv/libcsv.a $(top_builddir)/storage/googlestats/libgooglestats.a $(top_builddir)/storage/heap/libheap.a $(top_builddir)/storage/innodb_plugin/libinnobase.a $(top_builddir)/storage/myisam/libmyisam.a $(top_builddir)/storage/myisammrg/libmyisammrg.a
mysql_se_dirs =  archive blackhole csv example federated googlestats heap innobase innodb_plugin myisam myisammrg
mysql_se_distdirs =  archive blackhole csv example federated googlestats heap innobase innodb_plugin myisam myisammrg ndb
mysql_se_unittest_dirs =  ../storage/archive ../storage/blackhole ../storage/csv ../storage/example ../storage/federated ../storage/googlestats ../storage/heap ../storage/innobase ../storage/innodb_plugin ../storage/myisam ../storage/myisammrg
ncurses_dir = ncurses
ndb_bin_am_ldflags = 
ndb_cxxflags_fix = 
ndb_mgmclient_libs = 
ndb_opt_subdirs = 
ndb_port = 
ndb_transporter_opt_objs = 
ndbcluster_includes = 
ndbcluster_libs = 
ndbcluster_system_libs = 
netware_dir = 
oldincludedir = /usr/include
openssl_includes = -I/home/lq/projects/dist/mysql/include
openssl_libs = -L/home/lq/projects/dist/mysql/lib/ -lssl -lcrypto
pdfdir = ${docdir}
perftools_dir = google-perftools
plugin_archive_shared_target = ha_archive.la
plugin_archive_static_target = 
plugin_blackhole_shared_target = ha_blackhole.la
plugin_blackhole_static_target = 
plugin_csv_shared_target = 
plugin_csv_static_target = libcsv.a
plugin_example_shared_target = ha_example.la
plugin_example_static_target = 
plugin_federated_shared_target = ha_federated.la
plugin_federated_static_target = 
plugin_googlestats_shared_target = 
plugin_googlestats_static_target = libgooglestats.a
plugin_heap_shared_target = 
plugin_heap_static_target = libheap.a
plugin_innobase_shared_target = ha_innodb.la
plugin_innobase_static_target = 
plugin_innodb_plugin_shared_target = 
plugin_innodb_plugin_static_target = libinnobase.a
plugin_myisam_shared_target = 
plugin_myisam_static_target = libmyisam.a
plugin_myisammrg_shared_target = 
plugin_myisammrg_static_target = libmyisammrg.a
plugin_ndbcluster_shared_target = 
plugin_ndbcluster_static_target = 
plugin_partition_shared_target = 
plugin_partition_static_target = 
prefix = /home/lq/projects/dist/mysql
program_transform_name = s,x,x,
psdir = ${docdir}
readline_basedir = readline
readline_dir = cmd-line-utils/readline
readline_h_ln_cmd = $(LN) -s $(top_srcdir)/cmd-line-utils/readline readline
readline_link = $(top_builddir)/cmd-line-utils/readline/libreadline.a
readline_topdir = cmd-line-utils
sbindir = ${exec_prefix}/sbin
server_scripts = mysqld_safe mysql_install_db
sharedstatedir = ${prefix}/com
sql_client_dirs = strings mysys dbug extra regex libmysql libmysql_r client
sql_server = vio sql
sql_server_dirs = strings mysys dbug extra regex storage plugin
sql_union_dirs =  strings mysys dbug extra regex libmysql libmysql_r client  storage  plugin 
srcdir = .
subdirs =  lzo google-perftools ncurses
sysconfdir = /etc
target = x86_64-unknown-linux-gnu
target_alias = 
target_cpu = x86_64
target_os = linux-gnu
target_vendor = unknown
tools_dirs = server-tools
top_build_prefix = 
top_builddir = .
top_srcdir = .
uname_prog = /bin/uname
yassl_dir = 
yassl_h_ln_cmd = 
yassl_libs = 
yassl_taocrypt_extra_cxxflags = 
yassl_thread_cxxflags = 
zlib_dir = zlib
AUTOMAKE_OPTIONS = foreign

# These are built from source in the Docs directory
EXTRA_DIST = INSTALL-SOURCE INSTALL-WIN-SOURCE \
			README COPYING CMakeLists.txt

SUBDIRS = . include  zlib \
			ncurses lzo google-perftools \
			cmd-line-utils sql-common scripts \
			 strings mysys dbug extra regex libmysql libmysql_r client  storage  plugin  unittest \
			vio sql  tests \
			netware  \
			mysql-test support-files sql-bench server-tools \
			win

DIST_SUBDIRS = . include Docs zlib \
			cmd-line-utils sql-common scripts \
			strings mysys dbug extra regex libmysql libmysql_r client unittest storage plugin \
			vio sql man tests \
			netware libmysqld \
			mysql-test support-files sql-bench server-tools \
			win \
			BUILD

DISTCLEANFILES = ac_available_languages_fragment

#
# Headers which need to be checked for abi/api compatibility.
# API_PREPROCESSOR_HEADER will be used until mysql_priv.h stablizes
# after which TEST_PREPROCESSOR_HEADER will be used.
#
API_PREPROCESSOR_HEADER = $(top_srcdir)/include/mysql/plugin.h \
                           $(top_srcdir)/include/mysql.h

TEST_PREPROCESSOR_HEADER = $(top_srcdir)/include/mysql/plugin.h \
                            $(top_srcdir)/sql/mysql_priv.h \
                            $(top_srcdir)/include/mysql.h

all: all-recursive

.SUFFIXES:
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(RECURSIVE_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done
cscopelist-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) cscopelist); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)

clean-cscope:
	-rm -f cscope.files

cscope.files: clean-cscope cscopelist-recursive cscopelist

cscopelist: cscopelist-recursive $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS) $(LISP)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile all-local
installdirs: installdirs-recursive
installdirs-am:
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-libtool \
	distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am:

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am:

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am:

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) \
	cscopelist-recursive ctags-recursive install-am install-strip \
	tags-recursive

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am all-local am--refresh check check-am clean \
	clean-cscope clean-generic clean-libtool cscope cscopelist \
	cscopelist-recursive ctags ctags-recursive dist dist-all \
	dist-bzip2 dist-gzip dist-hook dist-lzip dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-generic \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-generic mostlyclean-libtool pdf pdf-am \
	ps ps-am tags tags-recursive uninstall uninstall-am


# Create permission databases
init-db:		all
	$(top_builddir)/scripts/mysql_install_db

bin-dist:		all
	$(top_builddir)/scripts/make_binary_distribution 

# Remove BK's "SCCS" subdirectories from source distribution
# Create initial database files for Windows installations and check them.
dist-hook:
	rm -rf `find $(distdir) -type d -name SCCS -print`
	mkdir -p $(distdir)/win
	scripts/mysql_install_db --no-defaults --cross-bootstrap \
		--builddir=$(top_builddir) \
		--datadir=$(distdir)/win/data \
		--srcdir=$(top_srcdir)
	storage/myisam/myisamchk --silent --fast $(distdir)/win/data/mysql/*.MYI

all-local:		abi_check	

tags:
	support-files/build-tags

.PHONY:	init-db bin-dist \
  test    test-force    test-full    test-force-full    test-force-mem \
  test-pl test-force-pl test-full-pl test-force-full-pl test-force-pl-mem \
  test-unit test-ps test-nr test-pr test-ns test-binlog-statement \
  test-ext-funcs test-ext-rpl test-ext-partitions test-ext-jp \
  test-ext-stress test-ext test-embedded test-reprepare \
  test-fast test-fast-cursor test-fast-view test-fast-prepare \
  test-full-qa

# Target 'test' will run the regression test suite using the built server.
#
# If you are running in a shared environment, users can avoid clashing
# port numbers by setting individual small numbers 1-100 to the
# environment variable MTR_BUILD_THREAD. The script "mysql-test-run"
# will then calculate the various port numbers it needs from this,
# making sure each user use different ports.

test-unit:
	cd unittest && $(MAKE) test

test-ps:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl $(force) --ps-protocol --mysqld=--binlog-format=mixed

test-nr:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl $(force) --mysqld=--binlog-format=row

test-pr:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl $(force) $(mem) --ps-protocol --mysqld=--binlog-format=row

test-ns:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl $(force) $(mem) --mysqld=--binlog-format=mixed

test-binlog-statement:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl $(force) --mysqld=--binlog-format=statement

# This code is duplicated in "test-bt", see the Changeset comment of 2007-Dec-07
test-embedded:
	if [ -e bin/mysqltest_embedded -o -e libmysqld/examples/mysqltest_embedded ] ; then \
	  cd mysql-test ; MTR_BUILD_THREAD=auto \
	      /usr/bin/perl ./mysql-test-run.pl --comment=embedded --force --timer \
	          --embedded-server --skip-rpl --skip-ndbcluster ; \
	else \
	  echo "no program found for 'embedded' tests - skipped testing" ; \
	fi

test-reprepare:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl $(force) $(mem) --ps-protocol \
		--mysqld=--debug=+d,reprepare_each_statement

test:	test-unit test-ns test-pr

smoke:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl --do-test=s

test-full:	test test-nr test-ps

test-force:
	$(MAKE) force=--force test

test-force-full:
	$(MAKE) force=--force test-full

#used by autopush.pl to run memory based tests
test-force-mem:
	$(MAKE) force=--force mem=--mem test

test-bt:
	-cd mysql-test ; MTR_BUILD_THREAD=auto \
	    /usr/bin/perl ./mysql-test-run.pl --comment=normal --force --timer \
	        --skip-ndbcluster --report-features
	-cd mysql-test ; MTR_BUILD_THREAD=auto \
	    /usr/bin/perl ./mysql-test-run.pl  --comment=ps    --force --timer \
	        --skip-ndbcluster --ps-protocol
	-if [ -e bin/ndbd -o -e storage/ndb/src/kernel/ndbd ] ; then \
	  cd mysql-test ; \
	    MTR_BUILD_THREAD=auto \
	      /usr/bin/perl ./mysql-test-run.pl --comment=ndb+ps --force --timer \
	          --ps-protocol --mysqld=--binlog-format=row --suite=ndb ; \
	    MTR_BUILD_THREAD=auto \
	      /usr/bin/perl ./mysql-test-run.pl --comment=ndb --force --timer \
	          --with-ndbcluster-only ; \
	else \
	  echo "no program found for 'ndbcluster' tests - skipped testing" ; \
	fi
	-cd mysql-test ; MTR_BUILD_THREAD=auto \
	    /usr/bin/perl ./mysql-test-run.pl --force --comment=funcs1+ps --ps-protocol --reorder --suite=funcs_1
	-cd mysql-test ; MTR_BUILD_THREAD=auto \
	    /usr/bin/perl ./mysql-test-run.pl --force --comment=funcs2 --suite=funcs_2
	-cd mysql-test ; MTR_BUILD_THREAD=auto \
	    /usr/bin/perl ./mysql-test-run.pl --force --comment=partitions --suite=parts
	-cd mysql-test ; MTR_BUILD_THREAD=auto \
	    /usr/bin/perl ./mysql-test-run.pl --force --comment=stress --suite=stress
	-cd mysql-test ; MTR_BUILD_THREAD=auto \
	    /usr/bin/perl ./mysql-test-run.pl --force --comment=jp --suite=jp
	-if [ -d mysql-test/suite/nist ] ; then \
	  cd mysql-test ; MTR_BUILD_THREAD=auto \
	      /usr/bin/perl ./mysql-test-run.pl --comment=nist --force --suite=nist ; \
	fi
	-if [ -d mysql-test/suite/nist ] ; then \
	  cd mysql-test ; MTR_BUILD_THREAD=auto \
	      /usr/bin/perl ./mysql-test-run.pl --comment=nist+ps --force --suite=nist --ps-protocol ; \
	fi
	-if [ -e bin/mysqltest_embedded -o -e libmysqld/examples/mysqltest_embedded ] ; then \
	  cd mysql-test ; MTR_BUILD_THREAD=auto \
	      /usr/bin/perl ./mysql-test-run.pl --comment=embedded --force --timer \
	          --embedded-server --skip-rpl --skip-ndbcluster ; \
	else \
	  echo "no program found for 'embedded' tests - skipped testing" ; \
	fi

test-bt-fast:
	-cd mysql-test ; MTR_BUILD_THREAD=auto \
	    /usr/bin/perl ./mysql-test-run.pl  --comment=ps    --force --timer \
	        --skip-ndbcluster --ps-protocol --report-features
	-if [ -e bin/ndbd -o -e storage/ndb/src/kernel/ndbd ] ; then \
	  cd mysql-test ; \
	    MTR_BUILD_THREAD=auto \
	      /usr/bin/perl ./mysql-test-run.pl --comment=ndb --force --timer \
	          --with-ndbcluster-only ; \
	else \
	  echo "no program found for 'ndbcluster' tests - skipped testing" ; \
	fi
	-cd mysql-test ; MTR_BUILD_THREAD=auto \
	    /usr/bin/perl ./mysql-test-run.pl --force --comment=stress --suite=stress

test-bt-debug:
	-cd mysql-test ; MTR_BUILD_THREAD=auto \
	    /usr/bin/perl ./mysql-test-run.pl --comment=debug  --force --timer \
	        --skip-ndbcluster --skip-rpl --report-features

test-bt-debug-fast:

test-bt-debug-fast:

# Keep these for a while
test-pl:	test
test-full-pl:	test-full
test-force-pl:	test-force
test-force-pl-mem:  test-force-mem
test-force-full-pl: test-force-full

test-ext-funcs:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl --force --reorder --suite=funcs_1 ; \
	    /usr/bin/perl ./mysql-test-run.pl --force --suite=funcs_2

test-ext-rpl:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl --force --suite=rpl

test-ext-partitions:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl --force --suite=parts

test-ext-jp:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl --force --suite=jp

test-ext-stress:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl --force --big-test --suite=stress

test-ext:	test-ext-funcs test-ext-rpl test-ext-partitions test-ext-jp test-ext-stress

test-fast:
	cd mysql-test ; \
	    /usr/bin/perl ./mysql-test-run.pl $(subset) --force --skip-ndb --skip-innodb --skip-im --skip-rpl ; \
	    /usr/bin/perl ./mysql-test-run.pl $(subset) --force --suite=funcs_1 --do-test=myisam ; \
	    /usr/bin/perl ./mysql-test-run.pl $(subset) --force --suite=stress --do-test=ddl_myisam 

test-fast-view:
	$(MAKE) subset=--view-protocol test-fast

test-fast-cursor:
	$(MAKE) subset=--cursor-protocol test-fast

test-fast-prepare:
	$(MAKE) subset=--ps-protocol test-fast

test-full-qa:
	$(MAKE) force=--force test-pr \
	    test-binlog-statement test-ext test-fast-view \
	        test-fast-cursor test-unit

#
# Rules for checking that the abi/api has not changed.
#
# The following steps are followed in the do_abi_check rule below
#
# 1) Generate preprocessor output for the files that need to
#    be tested for abi/api changes. use -nostdinc to prevent
#    generation of preprocessor output for system headers. This
#    results in messages in stderr saying that these headers
#    were not found. Redirect the stderr output to /dev/null
#    to prevent seeing these messages.
# 2) sed the output to 
#    2.1) remove blank lines and lines that begin with "# "
#    2.2) When gcc -E is run on the Mac OS  and solaris sparc platforms it
#         introduces a line of output that shows up as a difference between
#         the .pp and .out files. Remove these OS specific preprocessor text
#         inserted by the preprocessor.
# 3) diff the generated file and the canons (.pp files already in
#    the repository).
# 4) delete the .out file that is generated.
#
# If the diff fails, the generated file is not removed. This will
# be useful for analysis of ABI differences (e.g. using a visual
# diff tool).
#
# A ABI change that causes a build to fail will always be accompanied
# by new canons (.out files). The .out files that are not removed will
# be replaced as the new .pp files.
#
# e.g. If include/mysql/plugin.h has an ABI change then this rule would
# leave a <build directory>/abi_check.out file.
#
# A developer with a justified API change will then do a
# mv <build directory>/abi_check.out include/mysql/plugin.pp 
# to replace the old canons with the new ones.
#

abi_check:	$(API_PREPROCESSOR_HEADER)
	$(MAKE) abi_headers="$^" do_abi_check

abi_check_all:	$(TEST_PREPROCESSOR_HEADER)
	$(MAKE) abi_headers="$^" do_abi_check

do_abi_check:
	set -ex; \
	for file in $(abi_headers); do \
	         gcc -std=gnu99 -E -nostdinc -dI -DMYSQL_ABI_CHECK \
	                  -I$(top_srcdir)/include \
	                  -I$(top_srcdir)/include/mysql \
	                  -I$(top_srcdir)/sql \
	                  -I$(top_builddir)/include \
	                  -I$(top_builddir)/include/mysql \
	                  -I$(top_builddir)/sql \
	                                 $$file 2>/dev/null | \
	                  /bin/sed -e '/^# /d' \
	                            -e '/^[ 	]*$$/d' \
	                            -e '/^#pragma GCC set_debug_pwd/d' \
	                            -e '/^#ident/d' > \
	                                       $(top_builddir)/abi_check.out; \
	                  /usr/bin/diff -w $$file.pp $(top_builddir)/abi_check.out; \
	                  /bin/rm $(top_builddir)/abi_check.out; \
	done

# Don't update the files from bitkeeper
%::SCCS/s.%

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
